aoi: data/Country.gpkg
hex_res: 4
raster_like: data/blank_proj.tif

features:

  - name: ocean_dist
    type: vector
    operation: distance
    file: data/Country_oceans.gpkg
    decimals: 3
    fix:
      factor: 0.001

  - name: waterbody_dist
    type: vector
    operation: distance
    file: data/Country_waterbodies.gpkg
    decimals: 3
    fix:
      factor: 0.001

  - name: waterway_dist
    type: vector
    operation: distance
    file: data/Country_waterways.gpkg
    decimals: 3
    fix:
      factor: 0.001

  - name: road_dist
    type: vector
    operation: distance
    file: data/Country_roads.gpkg
    decimals: 3
    fix:
      factor: 0.001
